// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDikGJNunHwJJEww0mIj8o3AvvkHnZAeH0',
    appId: '1:723672844310:web:8042d0f3c15a0af8aa4d37',
    messagingSenderId: '723672844310',
    projectId: 'flutter-projects-45df9',
    authDomain: 'flutter-projects-45df9.firebaseapp.com',
    storageBucket: 'flutter-projects-45df9.appspot.com',
    measurementId: 'G-LE907CVVRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-zGTus9FREMs6wJgQxWW3RbCMyj3kFso',
    appId: '1:723672844310:android:ff670ea781d7fbb7aa4d37',
    messagingSenderId: '723672844310',
    projectId: 'flutter-projects-45df9',
    storageBucket: 'flutter-projects-45df9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGCGjnHz7l37IOIfVBx3rINBWeXD7rVOw',
    appId: '1:723672844310:ios:b97930d0266a4328aa4d37',
    messagingSenderId: '723672844310',
    projectId: 'flutter-projects-45df9',
    storageBucket: 'flutter-projects-45df9.appspot.com',
    iosClientId: '723672844310-6d7pqgpbj076q5i0e1d5r8580q2jij7k.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGCGjnHz7l37IOIfVBx3rINBWeXD7rVOw',
    appId: '1:723672844310:ios:71bdaf511274b77eaa4d37',
    messagingSenderId: '723672844310',
    projectId: 'flutter-projects-45df9',
    storageBucket: 'flutter-projects-45df9.appspot.com',
    iosClientId: '723672844310-ralrvq3iffhbjjm4rp77ph2gevj0jpmo.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushApp.RunnerTests',
  );
}
